### ISSUE TITLE
Words with less than three characters 

### ISSUE THREAD

**Issue by andreaspacher** [DuncanOgle/BooleanSearchParser#8]
Hello, thanks for this great parser! It works wonderful.

Many of your examples in the README-file contain inputs with words of less than 3 characters, such as `ict OR it`.

However, in my case it seems that words of less than 3 characters are ignored. Examples:

- `tu graz` (leads to 0 results, even though there should be plenty)
- `tu AND graz` (also leads to 0 results, even though there should be plenty)
- `tu OR graz` (only searches for `graz` while `tu` is being ignored)
- `"tu graz"` (same - only searches for `graz` while `tu` is being ignored)

But 3-letter-words work fine (e.g. `nyu` or `ulm`).

I am not overly proficient with coding. May I thus ask how one could fix that? 

Thanks a lot!

**Comment by DuncanOgle** [comment]
Hi @andreaspacher, it's been a while since I worked with PHP and MySQL, but if I recall correctly MySQL has a minimum word length when doing a full-text search. This is normally 3 or 4 characters, which is why your 2 letter words are being ignored.

Depending on how old the database you're working with (and operating system), there are a couple of different ways to change this value. It looks like you have to change it in a file, rather than just run a SQL command.

You're after a file called `my.cnf`. 

- If you're using a Mac/Linux machine then the file you're after is either `/etc/my.cnf` or `/etc/mysql/my.cnf`. 
- If you're on Windows and using something like WAMP or XAMPP then it should be here `C:\\wampp\mysql\bin\my.cnf` or `C:\\xampp\mysql\bin\my.cnf`.

From here you should find a variable called `ft_min_word_len` or `innodb_ft_min_token_size`. Set this to the value you want - 2 is probably the lowest number you want. 1 might give bad results or bad performance.

Once that's done, you'll need to "repair" the table you're trying to search to make it work `REPAIR TABLE your_table_name QUICK;`

I hope this helps. If you want to do your own research, then Googling `mysql full text search minimum word length` should help you find more results.

**Comment by andreaspacher** [comment]
Hello @DuncanOgle, thank you for the quick response - this is very helpful! It is good to know that the issue arises out of a default MySQL setting and not from the script's PHP code. Thanks also for pointing out how to fix that, I greatly appreciate it.
